# Generated by Django 2.2.4 on 2019-12-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='update_at',
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
