# Generated by Django 2.2.4 on 2019-12-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20191229_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='img',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='due',
            field=models.DateTimeField(default=''),
        ),
    ]
