# Generated by Django 2.2.4 on 2019-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_auto_20191229_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
